spring:
  profiles:
    active: @activatedProperties@
  http:
      multipart:
          maxFileSize: 64Mb
          maxRequestSize: 128Mb


mybatis:
     mapperLocations: classpath*:mybatis/**/*.xml
     typeAliasesPackage: com.flyingwillow.springbootproptype.domain
     mapperScanPackage: com.flyingwillow.springbootproptype.auto.mapper
     configLocation: classpath:mybatis_config.xml

thread:
    pool:
          corePoolSize: 20
          maxPoolSize: 50
          keepAliveSeconds: 300


nos:
    accessKey: 56895053996a40db876c6ba5a5e1a09b
    accessSecret: eee357caec3d4df980815580cee510f2
    nosHost: flyingwillow.springbootproptype
    cdnHost: flyingwillow.springbootproptype
    bucketName: auto

project:
    dir:
        root: @dir.home.root@
        htmlRoot: @dir.home.root@/htmlfile
        tmpRoot: @dir.home.root@/tmpdir


